Vagrant.configure(2) do |config|
	config.vm.box = "centos-7.0-dbs"
	config.vm.hostname = "dataops"
	config.vm.box_url = "file://dataops.box"
	config.vm.provision "shell", inline: <<-SHELL
		mysql -u root < /vagrant/data/mysql-users.sql
		mysql drupal < /vagrant/data/mysql-drupal.sql
		tar xfz /vagrant/queries.tgz
		ln -s /vagrant/bin bin && chown vagrant:vagrant bin
	SHELL
	config.vm.provision "shell", path: "scripts/vc-local.sh"
end
