# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :dataops2 do |dataops2_config|
	dataops2_config.vm.box = 'dataops_drupal'
	dataops2_config.vm.box_url = './testvm.box'
	dataops2_config.vm.hostname = 'dataops2'
	dataops2_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "4096"] 
	end
        dataops2_config.vm.network "forwarded_port", guest: 80, host: 8080
   end

end
