# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :dataops do |dataops_config|
	dataops_config.vm.box = 'dataops_drupal'
	dataops_config.vm.box_url = './mysql56_drupal.box'
	dataops_config.vm.hostname = 'dataops'
	dataops_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "4096"] 
	end
        dataops_config.vm.network "forwarded_port", guest: 80, host: 8080
   end

end
